import fs from "fs";
import path from "path";
import ts from "typescript";
import YAML from "yaml";
import type { TestAction, TestCaseDetailed, TestCaseStep } from "../types.js";

export interface LocalMetadata {
  formatVersion: 1;
  testFolder: string;
  testcase: string;
  application: string;
  description: string;
  detailedDescription?: string;
  priority: number | string;
  status: string;
  type: string;
  active: {
    default: boolean;
    QA: boolean;
    UAT: boolean;
    PROD: boolean;
  };
  conditionOperator?: string;
  properties?: unknown[];
}

export interface LocalState {
  formatVersion: 1;
  serverPayload: TestCaseDetailed;
}

export interface ValidationIssue {
  file: string;
  line?: number;
  message: string;
}

function literal(value: unknown): string {
  return JSON.stringify(value ?? "");
}

function renderAction(action: TestAction, indent = "        "): string[] {
  const prefix = indent + "await ";

  switch (action.action) {
    case "openUrl":
      return [`${prefix}page.goto(${literal(action.value1)});`];

    case "wait": {
      const ms = Number(action.value1 ?? 0);
      return [`${prefix}page.waitForTimeout(${Number.isFinite(ms) ? ms : literal(action.value1)});`];
    }

    case "executeJS": {
      const lines = [`${prefix}page.evaluate(() => {`];
      for (const line of String(action.value1 ?? "").split(/\r?\n/)) {
        lines.push(indent + "    " + line);
      }
      lines.push(indent + "});");
      return lines;
    }

    case "calculateProperty":
      return [`${prefix}cerberus.calculateProperty(${literal(action.value1)});`];

    default:
      return [
        `${prefix}cerberus.action(${literal(action.action)}, ${JSON.stringify({
          value1: action.value1,
          value2: action.value2,
          value3: action.value3,
          conditionOperator: action.conditionOperator,
          isFatal: action.isFatal,
          doScreenshotBefore: action.doScreenshotBefore,
          doScreenshotAfter: action.doScreenshotAfter,
          waitBefore: action.waitBefore,
          waitAfter: action.waitAfter,
          description: action.description,
        })});`,
      ];
  }
}

export function toLocalMetadata(test: TestCaseDetailed): LocalMetadata {
  return {
    formatVersion: 1,
    testFolder: test.testFolderId,
    testcase: test.testcaseId,
    application: test.application,
    description: test.description,
    detailedDescription: test.detailedDescription,
    priority: test.priority,
    status: test.status,
    type: test.type,
    active: {
      default: test.isActive,
      QA: test.isActiveQA,
      UAT: test.isActiveUAT,
      PROD: test.isActivePROD,
    },
    conditionOperator: test.conditionOperator,
    properties: test.properties ?? [],
  };
}

export function generateSpec(test: TestCaseDetailed): string {
  const lines: string[] = [
    "// Generated by Cerberus CLI.",
    "// Playwright-like DSL interpreted by Cerberus CLI; it is not executed by Playwright.",
    "",
    `test(${literal(test.description || test.testcaseId)}, async ({ page, cerberus }) => {`,
  ];

  for (const step of test.steps ?? []) {
    lines.push("");
    lines.push(
      `    await cerberus.step(${literal(step.description || `Step ${step.stepId}`)}, async () => {`
    );

    for (const action of [...(step.actions ?? [])].sort((a, b) => Number(a.sort) - Number(b.sort))) {
      lines.push(...renderAction(action));
    }

    lines.push("    });");
  }

  lines.push("});", "");
  return lines.join("\n");
}

export function writeLocalTest(testDir: string, test: TestCaseDetailed): void {
  fs.mkdirSync(path.join(testDir, ".cerberus"), { recursive: true });
  fs.writeFileSync(path.join(testDir, "cerberus.yaml"), YAML.stringify(toLocalMetadata(test)), "utf8");
  fs.writeFileSync(path.join(testDir, "test.spec.ts"), generateSpec(test), "utf8");
  const state: LocalState = { formatVersion: 1, serverPayload: test };
  fs.writeFileSync(
    path.join(testDir, ".cerberus", "state.json"),
    JSON.stringify(state, null, 2) + "\n",
    "utf8"
  );
}

function stringArg(call: ts.CallExpression, index: number): string | undefined {
  const arg = call.arguments[index];
  if (!arg) return undefined;
  if (ts.isStringLiteralLike(arg) || ts.isNoSubstitutionTemplateLiteral(arg)) return arg.text;
  if (ts.isNumericLiteral(arg)) return arg.text;
  return undefined;
}

function sourceLine(source: ts.SourceFile, node: ts.Node): number {
  return source.getLineAndCharacterOfPosition(node.getStart(source)).line + 1;
}

function parseActionCall(
  call: ts.CallExpression,
  source: ts.SourceFile,
  template: TestAction | undefined,
  issues: ValidationIssue[]
): TestAction | undefined {
  if (!ts.isPropertyAccessExpression(call.expression)) return undefined;

  const receiver = call.expression.expression;
  const method = call.expression.name.text;
  const base: TestAction = template
    ? { ...template, controls: [...(template.controls ?? [])] }
    : {
        testFolderId: "",
        testcaseId: "",
        stepId: 0,
        actionId: 0,
        sort: 0,
        conditionOperator: "always",
        action: "",
        isFatal: true,
        doScreenshotBefore: false,
        doScreenshotAfter: false,
        waitBefore: 0,
        waitAfter: 0,
        controls: [],
      };

  if (ts.isIdentifier(receiver) && receiver.text === "page") {
    if (method === "goto") {
      const value = stringArg(call, 0);
      if (value === undefined) {
        issues.push({ file: source.fileName, line: sourceLine(source, call), message: "page.goto() requires a literal URL." });
        return undefined;
      }
      return { ...base, action: "openUrl", value1: value };
    }

    if (method === "waitForTimeout") {
      const value = stringArg(call, 0);
      if (value === undefined) {
        issues.push({ file: source.fileName, line: sourceLine(source, call), message: "page.waitForTimeout() requires a literal duration." });
        return undefined;
      }
      return { ...base, action: "wait", value1: value };
    }

    if (method === "evaluate") {
      const fn = call.arguments[0];
      if (!fn || (!ts.isArrowFunction(fn) && !ts.isFunctionExpression(fn)) || !ts.isBlock(fn.body)) {
        issues.push({ file: source.fileName, line: sourceLine(source, call), message: "page.evaluate() requires an inline function body." });
        return undefined;
      }
      return {
        ...base,
        action: "executeJS",
        value1: fn.body.statements.map((statement) => statement.getText(source)).join("\n"),
      };
    }
  }

  if (ts.isIdentifier(receiver) && receiver.text === "cerberus" && method === "calculateProperty") {
    const value = stringArg(call, 0);
    if (value === undefined) {
      issues.push({
        file: source.fileName,
        line: sourceLine(source, call),
        message: "cerberus.calculateProperty() requires a literal property name.",
      });
      return undefined;
    }
    return { ...base, action: "calculateProperty", value1: value };
  }

  issues.push({
    file: source.fileName,
    line: sourceLine(source, call),
    message: `Unsupported Cerberus DSL expression: ${call.expression.getText(source)}`,
  });
  return undefined;
}

export function parseSpec(
  specPath: string,
  original: TestCaseDetailed
): { steps: TestCaseStep[]; issues: ValidationIssue[] } {
  const text = fs.readFileSync(specPath, "utf8");
  const source = ts.createSourceFile(specPath, text, ts.ScriptTarget.Latest, true, ts.ScriptKind.TS);
  const issues: ValidationIssue[] = [];
  const steps: TestCaseStep[] = [];

  const visit = (node: ts.Node): void => {
    if (
      ts.isCallExpression(node) &&
      ts.isPropertyAccessExpression(node.expression) &&
      ts.isIdentifier(node.expression.expression) &&
      node.expression.expression.text === "cerberus" &&
      node.expression.name.text === "step"
    ) {
      const description = stringArg(node, 0) ?? `Step ${steps.length + 1}`;
      const callback = node.arguments[1];

      if (!callback || (!ts.isArrowFunction(callback) && !ts.isFunctionExpression(callback)) || !ts.isBlock(callback.body)) {
        issues.push({
          file: specPath,
          line: sourceLine(source, node),
          message: "cerberus.step() requires an inline function.",
        });
        return;
      }

      const originalStep = original.steps?.[steps.length];
      const actions: TestAction[] = [];

      for (const statement of callback.body.statements) {
        if (!ts.isExpressionStatement(statement)) continue;
        let expression: ts.Expression = statement.expression;
        if (ts.isAwaitExpression(expression)) expression = expression.expression;
        if (!ts.isCallExpression(expression)) continue;

        const action = parseActionCall(expression, source, originalStep?.actions?.[actions.length], issues);
        if (!action) continue;

        action.sort = actions.length + 1;
        actions.push(action);
      }

      steps.push({
        ...(originalStep ?? {
          testFolderId: original.testFolderId,
          testcaseId: original.testcaseId,
          stepId: steps.length + 1,
          sort: steps.length + 1,
          loop: "onceIfConditionTrue",
          conditionOperator: "always",
          isUsingLibraryStep: false,
          libraryStepStepId: 0,
          isStepInUseByOtherTestcase: false,
          libraryStepSort: 0,
          isLibraryStep: false,
          isExecutionForced: false,
          actions: [],
        }),
        description,
        sort: steps.length + 1,
        actions,
      });

      return;
    }

    ts.forEachChild(node, visit);
  };

  visit(source);
  return { steps, issues };
}

export function readLocalTest(testDir: string): { data: TestCaseDetailed; issues: ValidationIssue[] } {
  const metadataPath = path.join(testDir, "cerberus.yaml");
  const specPath = path.join(testDir, "test.spec.ts");
  const statePath = path.join(testDir, ".cerberus", "state.json");

  if (!fs.existsSync(metadataPath)) throw new Error(`Missing ${metadataPath}`);
  if (!fs.existsSync(specPath)) throw new Error(`Missing ${specPath}`);
  if (!fs.existsSync(statePath)) throw new Error(`Missing ${statePath}; run cerberus pull first.`);

  const metadata = YAML.parse(fs.readFileSync(metadataPath, "utf8")) as LocalMetadata;
  const state = JSON.parse(fs.readFileSync(statePath, "utf8")) as LocalState;

  if (metadata.formatVersion !== 1 || state.formatVersion !== 1) {
    throw new Error(`Unsupported local format in ${testDir}`);
  }

  const data: TestCaseDetailed = {
    ...state.serverPayload,
    testFolderId: metadata.testFolder,
    testcaseId: metadata.testcase,
    application: metadata.application,
    description: metadata.description,
    detailedDescription: metadata.detailedDescription,
    priority: metadata.priority,
    status: metadata.status,
    type: metadata.type,
    isActive: metadata.active?.default ?? state.serverPayload.isActive,
    isActiveQA: metadata.active?.QA ?? state.serverPayload.isActiveQA,
    isActiveUAT: metadata.active?.UAT ?? state.serverPayload.isActiveUAT,
    isActivePROD: metadata.active?.PROD ?? state.serverPayload.isActivePROD,
    conditionOperator: metadata.conditionOperator ?? state.serverPayload.conditionOperator,
    properties: Array.isArray(metadata.properties)
      ? (metadata.properties as TestCaseDetailed["properties"])
      : state.serverPayload.properties,
  };

  const parsed = parseSpec(specPath, data);
  data.steps = parsed.steps;
  return { data, issues: parsed.issues };
}

export function findLocalTestDirs(baseDir: string): string[] {
  if (!fs.existsSync(baseDir)) return [];

  const result: string[] = [];

  for (const folder of fs.readdirSync(baseDir, { withFileTypes: true })) {
    if (!folder.isDirectory() || folder.name.startsWith(".")) continue;

    const folderPath = path.join(baseDir, folder.name);
    for (const testcase of fs.readdirSync(folderPath, { withFileTypes: true })) {
      if (!testcase.isDirectory() || testcase.name.startsWith(".")) continue;

      const testDir = path.join(folderPath, testcase.name);
      if (
        fs.existsSync(path.join(testDir, "cerberus.yaml")) &&
        fs.existsSync(path.join(testDir, "test.spec.ts"))
      ) {
        result.push(testDir);
      }
    }
  }

  return result;
}
